"""Generate run_fresh_validation_aligned.py"""
import pathlib

lines = []
lines.append('"""Phase 6 Aligned Validation: Leakage-free comparable evaluation.')
lines.append('Runs LSTM, GRU, TFT, Hybrid on PJM 2020. Same seed=42, 70/15/15 split.')
lines.append('No test leakage. One-step-ahead via predict=False windows. ~1282 aligned.')
lines.append('Results: results/fresh_validation_aligned/')
lines.append('"""')
lines.append('from __future__ import annotations')
lines.append('import json, logging, time')
lines.append('from pathlib import Path')
lines.append('import numpy as np')
lines.append('import pandas as pd')
lines.append('')
lines.append('logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('PROCESSED_DIR = Path("dataset/processed")')
lines.append('OUTPUT_DIR = Path("results/fresh_validation_aligned")')
lines.append('SEED = 42')
lines.append('TIME_IDX = "time_idx"')
lines.append('GROUP_ID = "group_id"')
lines.append('TARGET = "electricity_demand"')
lines.append('CANONICAL_TARGET = "target"')
lines.append('')
lines.append('')
lines.append('def load_data():')
lines.append('    train = pd.read_csv(PROCESSED_DIR / "train.csv")')
lines.append('    val = pd.read_csv(PROCESSED_DIR / "validation.csv")')
lines.append('    test = pd.read_csv(PROCESSED_DIR / "test.csv")')
lines.append('    logger.info("Loaded train=%d, val=%d, test=%d", len(train), len(val), len(test))')
lines.append('    return train, val, test')
lines.append('')
lines.append('')
lines.append('def get_model_features(train_df):')
lines.append('    exo = [c for c in ("solar", "wind") if c in train_df.columns]')
lines.append('    feature_names = [')
lines.append('        "hour", "day_of_week", "day_of_month", "month", "week_of_year",')
lines.append('        "is_weekend", "hour_sin", "hour_cos", "dow_sin", "dow_cos",')
lines.append('        "month_sin", "month_cos", "lag_1", "lag_24", "lag_168",')
lines.append('        "rolling_mean_24", "rolling_std_24", "rolling_mean_168", "rolling_std_168",')
lines.append('    ]')
lines.append('    return exo + feature_names')
lines.append('')
lines.append('')
lines.append('def build_tft_dataframes(train_df, val_df, test_df):')
lines.append('    from src.models.tft.dataset import validate_frame')
lines.append('')
lines.append('    def make_frame(df):')
lines.append('        out = df.copy()')
lines.append('        out[TARGET] = out[CANONICAL_TARGET].astype(float)')
lines.append('        out[TIME_IDX] = 0')
lines.append('        out[GROUP_ID] = "single"')
lines.append('        known = [c for c in ("hour", "day_of_week", "temperature", "solar", "wind")')
lines.append('                 if c in out.columns]')
lines.append('        ordered = ([TIME_IDX, GROUP_ID, TARGET] + known +')
lines.append('                   [c for c in out.columns if c not in [TIME_IDX, GROUP_ID, TARGET] + known])')
lines.append('        out = out[ordered]')
lines.append('        feature_cols = [c for c in ordered if c not in [TIME_IDX, GROUP_ID, TARGET]]')
lines.append('        out = out.dropna(subset=feature_cols).reset_index(drop=True)')
lines.append('        out[TIME_IDX] = np.arange(len(out))')
lines.append('        out[GROUP_ID] = "single"')
lines.append('        return validate_frame(out)')
lines.append('')
lines.append('    return make_frame(train_df), make_frame(val_df), make_frame(test_df)')
lines.append('')
lines.append('')
lines.append('def integrity_check(model_name, y_true, y_pred, timestamps, train_rows, val_rows, test_rows):')
lines.append('    yt = np.asarray(y_true, dtype=float).ravel()')
lines.append('    yp = np.asarray(y_pred, dtype=float).ravel()')
lines.append('    ts = np.asarray(timestamps)')
lines.append('    n = len(yt)')
lines.append('    sse = float(np.sum((yt - yp) ** 2))')
lines.append('    yt_mean = float(np.mean(yt))')
lines.append('    sst = float(np.sum((yt - yt_mean) ** 2))')
lines.append('    r2_calc = 1.0 - sse / sst if sst > 0 else 0.0')
lines.append('    return {')
lines.append('        "model": model_name, "train_rows": train_rows, "val_rows": val_rows,')
lines.append('        "test_rows": test_rows, "prediction_count": n,')
lines.append('        "first_timestamp": str(ts[0]) if n > 0 else None,')
lines.append('        "last_timestamp": str(ts[-1]) if n > 0 else None,')
lines.append('        "nan": bool(np.isnan(yt).any() or np.isnan(yp).any()),')
lines.append('        "inf": bool(np.isinf(yt).any() or np.isinf(yp).any()),')
lines.append('        "const_prediction": bool(np.std(yp) < 1e-12) if n > 1 else False,')
lines.append('        "duplicate_timestamps": bool(len(ts) != len(np.unique(ts))),')
lines.append('        "unique_timestamps": len(np.unique(ts)),')
lines.append('        "chronological_order": bool(np.all(ts[:-1] <= ts[1:])) if n > 1 else True,')
lines.append('        "r2_calculated": r2_calc,')
lines.append('    }')

# Write part 1
target = pathlib.Path(r'D:\SmartGrid_AI_Research\run_fresh_validation_aligned.py')
with open(target, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Part 1 written: {len(lines)} lines')
