"""Append part 3: TFT runner"""
import pathlib

lines = []
lines.append('')
lines.append('')
lines.append('def run_tft(train_df, val_df, test_df):')
lines.append('    import torch')
lines.append('    from src.evaluation.metrics import evaluate_regression')
lines.append('    from src.models.baseline import load_params')
lines.append('    from src.models.tft import TemporalFusionTransformerForecaster')
lines.append('    from src.models.tft.dataset import validate_frame')
lines.append('    from pytorch_forecasting import TimeSeriesDataSet')
lines.append('')
lines.append('    t0 = time.time()')
lines.append('')
lines.append('    tft_train_df, tft_val_df, tft_test_df = build_tft_dataframes(train_df, val_df, test_df)')
lines.append('')
lines.append('    tft_trainval_df = pd.concat([tft_train_df, tft_val_df], ignore_index=True)')
lines.append('    tft_trainval_df[TIME_IDX] = np.arange(len(tft_trainval_df))')
lines.append('    tft_trainval_df = tft_trainval_df.sort_values([GROUP_ID, TIME_IDX]).reset_index(drop=True)')
lines.append('    tft_trainval_df = validate_frame(tft_trainval_df)')
lines.append('')
lines.append('    logger.info("TFT training on train+val: %d rows (NO test leakage)", len(tft_trainval_df))')
lines.append('    tft_params = load_params("tft")')
lines.append('    tft_model = TemporalFusionTransformerForecaster(**tft_params)')
lines.append('    tft_model.fit(tft_trainval_df)')
lines.append('')
lines.append('    full_df = pd.concat([tft_train_df, tft_val_df, tft_test_df], ignore_index=True)')
lines.append('    full_df[TIME_IDX] = np.arange(len(full_df))')
lines.append('    full_df = full_df.sort_values([GROUP_ID, TIME_IDX]).reset_index(drop=True)')
lines.append('    full_df = validate_frame(full_df)')
lines.append('')
lines.append('    test_min_ti = int(tft_test_df[TIME_IDX].min())')
lines.append('    test_max_ti = int(tft_test_df[TIME_IDX].max())')
lines.append('    logger.info("TFT test time_idx range: %d - %d", test_min_ti, test_max_ti)')
lines.append('')
lines.append('    all_preds = []')
lines.append('    all_actuals = []')
lines.append('    all_times = []')
lines.append('')
lines.append('    assert tft_model._training is not None')
lines.append('    for name, g in full_df.groupby(GROUP_ID, sort=True):')
lines.append('        g = g.sort_values(TIME_IDX).reset_index(drop=True)')
lines.append('        ds = TimeSeriesDataSet.from_dataset(')
lines.append('            tft_model._training, g, predict=False, stop_randomization=True')
lines.append('        )')
lines.append('        loader = ds.to_dataloader(')
lines.append('            train=False, batch_size=tft_model.batch_size, num_workers=0')
lines.append('        )')
lines.append('        med = tft_model._median_for_loader(loader).cpu().numpy()')
lines.append('')
lines.append('        times_per_window = []')
lines.append('        with torch.no_grad():')
lines.append('            for batch in loader:')
lines.append('                x = batch[0] if isinstance(batch, (list, tuple)) else batch')
lines.append('                times_per_window.append(np.asarray(x["decoder_time_idx"].cpu()))')
lines.append('        times = np.concatenate(times_per_window, axis=0)')
lines.append('')
lines.append('        target_by_time = dict(zip(g[TIME_IDX].tolist(), g[TARGET].tolist()))')
lines.append('')
lines.append('        for i in range(times.shape[0]):')
lines.append('            t = int(times[i, 0])')
lines.append('            if t < test_min_ti:')
lines.append('                continue')
lines.append('            all_preds.append(float(med[i, 0]))')
lines.append('            all_actuals.append(target_by_time[t])')
lines.append('            all_times.append(t)')
lines.append('')
lines.append('    preds_arr = np.asarray(all_preds, dtype=float)')
lines.append('    actuals_arr = np.asarray(all_actuals, dtype=float)')
lines.append('    times_arr = np.asarray(all_times)')
lines.append('')
lines.append('    metrics = evaluate_regression(actuals_arr, preds_arr)')
lines.append('    runtime = time.time() - t0')
lines.append('')
lines.append('    result = {')
lines.append('        "MAE": metrics["MAE"], "RMSE": metrics["RMSE"],')
lines.append('        "sMAPE": metrics["sMAPE"], "R2": metrics["R2"],')
lines.append('        "runtime": round(runtime, 2), "n_test": len(preds_arr),')
lines.append('        "pred_mean": float(np.mean(preds_arr)),')
lines.append('        "pred_min": float(np.min(preds_arr)),')
lines.append('        "pred_max": float(np.max(preds_arr)),')
lines.append('        "first_aligned_timestamp": str(times_arr[0]) if len(times_arr) > 0 else None,')
lines.append('        "last_aligned_timestamp": str(times_arr[-1]) if len(times_arr) > 0 else None,')
lines.append('        "train_rows": len(tft_train_df), "val_rows": len(tft_val_df),')
lines.append('        "test_rows": len(tft_test_df),')
lines.append('    }')
lines.append('')
lines.append('    logger.info("TFT: MAE=%.4f R2=%.4f n_test=%d (%.1fs)",')
lines.append('                metrics["MAE"], metrics["R2"], len(preds_arr), runtime)')
lines.append('')
lines.append('    return result, (actuals_arr, preds_arr, times_arr)')

target = pathlib.Path(r'D:\SmartGrid_AI_Research\run_fresh_validation_aligned.py')
with open(target, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Part 3 appended: {len(lines)} lines')
