"""Append part 2: LSTM/GRU runner"""
import pathlib

lines = []
lines.append('')
lines.append('')
lines.append('def run_lstm_gru(train_df, val_df, test_df, model_features):')
lines.append('    from src.data.adapters import tabular_ready')
lines.append('    from src.models.deep.sequence import build_windows')
lines.append('    from src.training.experiment_runner import ExperimentRunner')
lines.append('')
lines.append('    X_tr, y_tr, _, _ = tabular_ready(train_df, model_features)')
lines.append('    X_va, y_va, _, _ = tabular_ready(val_df, model_features)')
lines.append('    X_te, y_te, _, _ = tabular_ready(test_df, model_features)')
lines.append('')
lines.append('    X_tr_w, y_tr_w = build_windows(X_tr, y_tr, 24, 1)')
lines.append('    X_va_w, y_va_w = build_windows(X_va, y_va, 24, 1)')
lines.append('    X_te_w, y_te_w = build_windows(X_te, y_te, 24, 1)')
lines.append('    X_seq_all = np.vstack([X_tr_w, X_va_w, X_te_w])')
lines.append('    y_seq_all = np.concatenate([y_tr_w, y_va_w, y_te_w])')
lines.append('')
lines.append('    runner = ExperimentRunner(')
lines.append('        output_dir=str(OUTPUT_DIR / "runner_tmp"),')
lines.append('        train_ratio=0.70, val_ratio=0.15,')
lines.append('        use_validation=True, use_early_stopping=False, seed=SEED,')
lines.append('    )')
lines.append('')
lines.append('    results = {}')
lines.append('    predictions_arrays = {}')
lines.append('    for name in ["lstm", "gru"]:')
lines.append('        t0 = time.time()')
lines.append('        row, y_aligned, preds = runner.run_one(name, X_seq_all, y_seq_all)')
lines.append('        runtime = time.time() - t0')
lines.append('')
lines.append('        r2_val = row["R2"]')
lines.append('        sse = float(np.sum((y_aligned - preds) ** 2))')
lines.append('        yt_mean = float(np.mean(y_aligned))')
lines.append('        sst = float(np.sum((y_aligned - yt_mean) ** 2))')
lines.append('        r2_calc = 1.0 - sse / sst if sst > 0 else 0.0')
lines.append('')
lines.append('        n_pred = len(preds)')
lines.append('        has_nan = bool(np.isnan(preds).any())')
lines.append('        has_inf = bool(np.isinf(preds).any())')
lines.append('        is_const = bool(np.std(preds) < 1e-12) if n_pred > 1 else False')
lines.append('')
lines.append('        results[name] = {')
lines.append('            "MAE": row["MAE"], "RMSE": row["RMSE"], "sMAPE": row["sMAPE"],')
lines.append('            "R2": r2_val, "runtime": round(runtime, 2), "n_test": n_pred,')
lines.append('            "r2_identity_match": abs(r2_val - r2_calc) < 1e-6,')
lines.append('            "nan": has_nan, "inf": has_inf, "const": is_const,')
lines.append('            "train_rows": int(len(X_tr_w)), "val_rows": int(len(X_va_w)),')
lines.append('            "test_rows": int(len(X_te_w)),')
lines.append('            "pred_mean": float(np.mean(preds)),')
lines.append('            "pred_min": float(np.min(preds)),')
lines.append('            "pred_max": float(np.max(preds)),')
lines.append('        }')
lines.append('        predictions_arrays[name] = (y_aligned, preds)')
lines.append('        logger.info("%s: MAE=%.4f R2=%.4f n_test=%d (%.1fs)",')
lines.append('                     name.upper(), row["MAE"], r2_val, n_pred, runtime)')
lines.append('')
lines.append('    return results, predictions_arrays')

target = pathlib.Path(r'D:\SmartGrid_AI_Research\run_fresh_validation_aligned.py')
with open(target, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Part 2 appended: {len(lines)} lines')
