"""Append part 5: Main function with alignment, integrity checks, and output"""
import pathlib

lines = []
lines.append('')
lines.append('')
lines.append('def main():')
lines.append('    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)')
lines.append('    logger.info("=" * 60)')
lines.append('    logger.info("PHASE 6 ALIGNED VALIDATION")')
lines.append('    logger.info("=" * 60)')
lines.append('')
lines.append('    train_df, val_df, test_df = load_data()')
lines.append('    model_features = get_model_features(train_df)')
lines.append('    logger.info("Model features (%d): %s", len(model_features), model_features)')
lines.append('')
lines.append('    logger.info("=" * 40)')
lines.append('    logger.info("Running LSTM and GRU")')
lines.append('    logger.info("=" * 40)')
lines.append('    lstm_gru_results, lstm_gru_preds = run_lstm_gru(train_df, val_df, test_df, model_features)')
lines.append('')
lines.append('    logger.info("=" * 40)')
lines.append('    logger.info("Running TFT (train+val only, predict=False windows)")')
lines.append('    logger.info("=" * 40)')
lines.append('    tft_result, tft_data = run_tft(train_df, val_df, test_df)')
lines.append('')
lines.append('    logger.info("=" * 40)')
lines.append('    logger.info("Running Hybrid (train+val only, predict=False windows)")')
lines.append('    logger.info("=" * 40)')
lines.append('    hyb_result, hyb_data = run_hybrid(train_df, val_df, test_df)')
lines.append('')
lines.append('    integrity_results = []')
lines.append('')
lines.append('    for name in ["lstm", "gru"]:')
lines.append('        y_true, preds = lstm_gru_preds[name]')
lines.append('        r = lstm_gru_results[name]')
lines.append('        ts = np.arange(len(y_true))')
lines.append('        ic = integrity_check(name, y_true, preds, ts,')
lines.append('                             r["train_rows"], r["val_rows"], r["test_rows"])')
lines.append('        ic["r2_reported"] = r["R2"]')
lines.append('        ic["r2_match"] = abs(ic["r2_reported"] - ic["r2_calculated"]) < 1e-6')
lines.append('        integrity_results.append(ic)')
lines.append('        logger.info("%s integrity: n=%d nan=%s inf=%s const=%s r2_match=%s",')
lines.append('                     name, ic["prediction_count"], ic["nan"], ic["inf"],')
lines.append('                     ic["const_prediction"], ic["r2_match"])')
lines.append('')
lines.append('    y_true_t, preds_t, ts_t = tft_data')
lines.append('    ic_t = integrity_check("tft", y_true_t, preds_t, ts_t,')
lines.append('                           tft_result["train_rows"], tft_result["val_rows"], tft_result["test_rows"])')
lines.append('    ic_t["r2_reported"] = tft_result["R2"]')
lines.append('    ic_t["r2_match"] = abs(ic_t["r2_reported"] - ic_t["r2_calculated"]) < 1e-6')
lines.append('    integrity_results.append(ic_t)')
lines.append('    logger.info("TFT integrity: n=%d nan=%s inf=%s const=%s r2_match=%s",')
lines.append('                 ic_t["prediction_count"], ic_t["nan"], ic_t["inf"],')
lines.append('                 ic_t["const_prediction"], ic_t["r2_match"])')
lines.append('')
lines.append('    y_true_h, preds_h, ts_h = hyb_data')
lines.append('    ic_h = integrity_check("hybrid", y_true_h, preds_h, ts_h,')
lines.append('                           hyb_result["train_rows"], hyb_result["val_rows"], hyb_result["test_rows"])')
lines.append('    ic_h["r2_reported"] = hyb_result["R2"]')
lines.append('    ic_h["r2_match"] = abs(ic_h["r2_reported"] - ic_h["r2_calculated"]) < 1e-6')
lines.append('    integrity_results.append(ic_h)')
lines.append('    logger.info("Hybrid integrity: n=%d nan=%s inf=%s const=%s r2_match=%s",')
lines.append('                 ic_h["prediction_count"], ic_h["nan"], ic_h["inf"],')
lines.append('                 ic_h["const_prediction"], ic_h["r2_match"])')
lines.append('')
lines.append('    logger.info("=" * 40)')
lines.append('    logger.info("LEAKAGE VERIFICATION")')
lines.append('    logger.info("=" * 40)')
lines.append('    train_ts_max = train_df["timestamp"].max()')
lines.append('    val_ts_min = val_df["timestamp"].min()')
lines.append('    val_ts_max = val_df["timestamp"].max()')
lines.append('    test_ts_min = test_df["timestamp"].min()')
lines.append('    logger.info("Train max: %s", train_ts_max)')
lines.append('    logger.info("Val min: %s", val_ts_min)')
lines.append('    logger.info("Val max: %s", val_ts_max)')
lines.append('    logger.info("Test min: %s", test_ts_min)')
lines.append('    assert str(train_ts_max) < str(val_ts_min), "LEAKAGE: train >= val"')
lines.append('    assert str(val_ts_max) < str(test_ts_min), "LEAKAGE: val >= test"')
lines.append('    logger.info("No temporal overlap between train/val/test: PASS")')
lines.append('')
lines.append('    save_json = lambda obj, name: json.dump(obj, open(OUTPUT_DIR / name, "w"), indent=2, default=str)')
lines.append('')
lines.append('    save_json({"lstm": lstm_gru_results["lstm"], "gru": lstm_gru_results["gru"]}, "lstm_gru.json")')
lines.append('    save_json({"tft": tft_result}, "tft.json")')
lines.append('    save_json({"hybrid": hyb_result}, "hybrid.json")')
lines.append('    save_json(integrity_results, "integrity.json")')
lines.append('')
lines.append('    summary = {')
lines.append('        "phase": "6 aligned validation",')
lines.append('        "seed": SEED,')
lines.append('        "split": "70/15/15 chronological",')
lines.append('        "train_rows": len(train_df),')
lines.append('        "val_rows": len(val_df),')
lines.append('        "test_rows": len(test_df),')
lines.append('        "leakage_check": "PASS",')
lines.append('        "lstm_gru_results": lstm_gru_results,')
lines.append('        "tft_result": tft_result,')
lines.append('        "hybrid_result": hyb_result,')
lines.append('        "n_models": 4,')
lines.append('        "ablation_run": False,')
lines.append('        "multiyear_run": False,')
lines.append('    }')
lines.append('    save_json(summary, "summary.json")')
lines.append('')
lines.append('    print("\\n" + "=" * 60)')
lines.append('    print("PHASE 6 ALIGNED VALIDATION SUMMARY")')
lines.append('    print("=" * 60)')
lines.append('    for name in ["lstm", "gru"]:')
lines.append('        r = lstm_gru_results[name]')
lines.append('        print(f"  {name.upper()}: MAE={r[\'MAE\']:.4f} RMSE={r[\'RMSE\']:.4f} R2={r[\'R2\']:.4f} n={r[\'n_test\']}")')
lines.append('    r = tft_result')
lines.append('    print(f"  TFT:    MAE={r[\'MAE\']:.4f} RMSE={r[\'RMSE\']:.4f} R2={r[\'R2\']:.4f} n={r[\'n_test\']}")')
lines.append('    r = hyb_result')
lines.append('    print(f"  Hybrid: MAE={r[\'MAE\']:.4f} RMSE={r[\'RMSE\']:.4f} R2={r[\'R2\']:.4f} n={r[\'n_test\']}")')
lines.append('    print("=" * 60)')
lines.append('    print(f"Results saved to: {OUTPUT_DIR}")')
lines.append('    print("2020-2025 multi-year validation: NOT started")')
lines.append('    print("Ablation: NOT started")')
lines.append('    print("=" * 60)')
lines.append('')
lines.append('')
lines.append('if __name__ == "__main__":')
lines.append('    main()')

target = pathlib.Path(r'D:\SmartGrid_AI_Research\run_fresh_validation_aligned.py')
with open(target, 'a', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Part 5 appended: {len(lines)} lines')
